  name: Build
  on: push
  jobs:      
    build-ci:
      runs-on: macos-latest
      name: Mac Build
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install .NET 6.0.300-preview.22204.3
          run: |
              curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 6.0.300-preview.22204.3 --quality preview
              dotnet --version
              
        - name: Restore Dependencies
          run: dotnet restore src/Makani/Makani.csproj

        - name: Build Makani
          run: dotnet build src/Makani/Makani.csproj -c Release
        
        - name: Run unit tests
          run: dotnet test ./src/Makani.Tests --collect:"XPlat Code Coverage" --settings coverlet.runsettings
        
        # https://github.com/coverallsapp/github-action/issues/36
        - name: Get path to lcov file
          id: get_lcov_path
          shell: bash
          run: printf '::set-output name=lcov_path::%s\n' TestResults/*/coverage.info

        - name: Publish coverage report to coveralls.io   
          uses: coverallsapp/github-action@master   
          with:
            github-token: ${{ secrets.COVERALLS_TOKEN }} 
            path-to-lcov: ${{ steps.get_lcov_path.outputs.lcov_path }}